---
- name: WSL Init for ansible
  hosts: localhost
  roles:
  - python

- name: WSL Setup
  hosts: localhost
  roles:
  - andrewrothstein.terraform
  - andrewrothstein.terragrunt
  - azure
  - bitwarden-cli
  - strongswan-pki