---
- name: WSL Init
  hosts: localhost
  roles:
  - bitwarden-cli
  #- python
- name: WSL Setup
  hosts: localhost
  roles:
  - andrewrothstein.terraform
  - andrewrothstein.terragrunt
  - azure