---
- name: WSL Init for ansible
  hosts: localhost
  roles:
  - python

- name: WSL Setup
  hosts: localhost
  roles:
  - azure
  - bitwarden-cli
  tasks:
  - name: install terraform
    when: ansible_distribution == "Ubuntu"
    include_role:
      name: andrewrothstein.terraform

  - name: install terragrunt
    when: ansible_distribution == "Ubuntu"
    include_role:
      name: andrewrothstein.terragrunt